name: Build and Release
on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  VERSION: v0.2
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        draft: false
        prerelease: false

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Build HostPlugin
      run: |
        Invoke-WebRequest -Uri 'https://www.7-zip.org/a/7z2201-x64.exe' -OutFile '7z.exe'
        Start-Process .\7z.exe -ArgumentList '/S' -Wait
        Invoke-WebRequest -Uri 'https://github.com/skywind3000/PyStand/releases/download/1.1.0/PyStand-py38-pyqt5-lite.7z' -OutFile 'PyStand.7z' & 'C:\Program Files\7-Zip\7z.exe' x .\PyStand.7z -y -o"$env:GITHUB_WORKSPACE\PyStand-py38-pyqt5-lite"
        pip install virtualenv
        python -m virtualenv env
        .\env\Scripts\activate
        pip install pystray
        pip install pyncm
        pip install win10toast
        mv "$env:GITHUB_WORKSPACE\env\Lib\site-packages\*" "$env:GITHUB_WORKSPACE\PyStand-py38-pyqt5-lite\site-packages\" & 'C:\Program Files\7-Zip\7z.exe' a -t7z NeteaseTip.7z "$env:GITHUB_WORKSPACE\PyStand-py38-pyqt5-lite" -mx=9 -m0=LZMA2 & 'C:\Program Files\7-Zip\7z.exe' x "$env:GITHUB_WORKSPACE\lzma2201.7z" -y
        mv "$env:GITHUB_WORKSPACE\bin\7zSD.sfx" "$env:GITHUB_WORKSPACE"
        @"
        ;!@Install@!UTF-8!
        InstallPath="%AppData%\\Roaming\\NeteaseTip"
        Progress="no"
        RunProgram="PyStand.exe /T:%%T"
        ;!@InstallEnd@!
        "@ | Set-Content -Path "$env:GITHUB_WORKSPACE\config.txt" -Encoding UTF8
        copy /b 7zS.sfx + config.txt + NeteaseTip.7z NeteaseTip.exe

    - name: Upload Release HostPlugin
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: NeteaseTip.exe
        asset_name: NeteaseTip.exe
        asset_content_type: application/x-msdownload
