name: Build and Release
on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  VERSION: v0.2
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        draft: false
        prerelease: false

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Build NeteaseTip
      run: |
        cd "D:\a\NeteaseTip\NeteaseTip"
        Invoke-WebRequest -Uri 'https://github-blog-1314730533.cos.ap-beijing.myqcloud.com/7z2201-extra.zip' -OutFile 7z2201-extra.zip
        Invoke-WebRequest -Uri 'https://github-blog-1314730533.cos.ap-beijing.myqcloud.com/PyStand-py38-pyqt5-lite.7z' -OutFile 'PyStand.7z' 
        Expand-Archive -Path "7z2201-extra.zip" -DestinationPath "D:\a\NeteaseTip\NeteaseTip"
        D:\a\NeteaseTip\NeteaseTip\7z2201-extra\7za.exe x .\PyStand.7z -y -o"D:\a\NeteaseTip\NeteaseTip\PyStand"
        pip install virtualenv
        python -m virtualenv env
        .\env\Scripts\activate
        pip install pystray
        pip install pyncm
        pip install win10toast
        dir
        mv .\env\Lib\site-packages\* .\PyStand\PyStand-py38-pyqt5-lite\site-packages\
        mv main.py -Destination .\PyStand\PyStand-py38-pyqt5-lite\PyStand.int -Force
        D:\a\NeteaseTip\NeteaseTip\7z2201-extra\7za.exe a -t7z NeteaseTip.7z .\PyStand\PyStand-py38-pyqt5-lite\* -r -mx=9 -m0=LZMA2
        Invoke-WebRequest -Uri 'https://www.7-zip.org/a/lzma2201.7z' -OutFile lzma2201.7z
        D:\a\NeteaseTip\NeteaseTip\7z2201-extra\7za.exe x .\lzma2201.7z -y
        mv .\bin\7zSD.sfx .\
        Invoke-WebRequest -Uri 'https://github-blog-1314730533.cos.ap-beijing.myqcloud.com/config.txt' -OutFile config.txt
        cmd
        copy /b 7zSD.sfx + config.txt + NeteaseTip.7z NeteaseTip.exe

    - name: Upload Release HostPlugin
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: NeteaseTip.exe
        asset_name: NeteaseTip.exe
        asset_content_type: application/x-msdownload
