name: Build and Release
on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  VERSION: v0.2
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        draft: false
        prerelease: false

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Build NeteaseTip
      run: |
        cd "D:\a\NeteaseTip\NeteaseTip"
        Invoke-WebRequest -Uri 'https://www.7-zip.org/a/7z2201-x64.exe' -OutFile '.\7z.exe'
        Start-Process .\7z.exe -ArgumentList '/S' -Wait
        Invoke-WebRequest -Uri 'https://github.com/skywind3000/PyStand/releases/download/1.1.0/PyStand-py38-pyqt5-lite.7z' -OutFile 'PyStand.7z' & .\7z.exe x .\PyStand.7z -y -o.\PyStand-py38-pyqt5-lite
        pip install virtualenv
        python -m virtualenv env
        .\env\Scripts\activate
        pip install pystray
        pip install pyncm
        pip install win10toast
        dir
        mv D:\a\NeteaseTip\NeteaseTip\env\Lib\site-packages\* D:\a\NeteaseTip\NeteaseTip\PyStand-py38-pyqt5-lite\site-packages\
        D:\a\NeteaseTip\NeteaseTip\7z.exe a -t7z NeteaseTip.7z D:\a\NeteaseTip\NeteaseTip\PyStand-py38-pyqt5-lite -mx=9 -m0=LZMA2
        D:\a\NeteaseTip\NeteaseTip\7z.exe x D:\a\NeteaseTip\NeteaseTip\lzma2201.7z -y
        mv D:\a\NeteaseTip\NeteaseTip\bin\7zSD.sfx D:\a\NeteaseTip\NeteaseTip\
        @"
        ;!@Install@!UTF-8!
        InstallPath="%AppData%\\Roaming\\NeteaseTip"
        Progress="no"
        RunProgram="PyStand.exe /T:%%T"
        ;!@InstallEnd@!
        "@ | Set-Content -Path D:\a\NeteaseTip\NeteaseTip\config.txt -Encoding UTF8
        copy /b D:\a\NeteaseTip\NeteaseTip\7zS.sfx + D:\a\NeteaseTip\NeteaseTip\config.txt + D:\a\NeteaseTip\NeteaseTip\NeteaseTip.7z NeteaseTip.exe

    - name: Upload Release HostPlugin
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: NeteaseTip.exe
        asset_name: NeteaseTip.exe
        asset_content_type: application/x-msdownload
